### ISSUE TITLE
Close Unmodified Fails on Windows

### ISSUE THREAD

**Issue by jercle** [gschrader/tabs-closer#3]
Hi, 

The Close Unmodified Tabs menu doesn't seem to work on Windows

**Comment by gschrader** [comment]
I've just tried on Atom 1.5.3/Tabs-closer 0.13.0 in Windows and it seems to work. Are those the same versions you have?

**Comment by jercle** [comment]
I've got Atom Version: 1.5.3/Tabs-closer 0.13.0/Microsoft Windows 10 Home

**Comment by gschrader** [comment]
I'm not sure what this might be, does anything show up in the error console? Have a peek in the dev tools, Ctrl-Alt-I and select the console tab.

I need to ask as well, the files you are expecting to be closed, they are under a git project directory?

**Comment by jercle** [comment]
Hi, yeah the files were under a git project. I uninstalled and reinstalled and it works fine now. So maybe I had something interfering. Works perfectly now
