### ISSUE TITLE
Take all repositories into account

### ISSUE THREAD

**Issue by simon04** [gschrader/tabs-closer#4]
First of all: Thank you for the nice plugin!

When using multiple project folders, each having their own Git repository, "Close Unmodified Tabs" closes all modified tabs from the second project folder/repository since due to 0fe25413e3c0381c9290f4f22091e426887b5ce3 it only takes the first repository into account.

**Comment by gschrader** [comment]
Thanks for reporting this should be fixed in 0.14.0
